//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

pub use super::candy::Entity as Candy;
pub use super::points::Entity as Points;
pub use super::rewards::Entity as Rewards;
pub use super::rewards_pool::Entity as RewardsPool;
pub use super::tasks::Entity as Tasks;
pub use super::users::Entity as Users;
