database:
  #db_url: "postgres://test:123456@0.0.0.0:5433/nostr_gateway"
  db_url: "postgres://zhangwei:zhangwei@0.0.0.0:5432/mydb"
  max_connect_pool: 30
  min_connect_pool: 10
  connect_timeout: 30
  acquire_timeout: 60
server:
  host: "0.0.0.0"
  port: "8080"
auth:
  client_id: ""
  client_secret: ""
  redirect_url: "http://localhost:8080/auth/callback"
